.SUFFIXES: .srs

srcs = abcd0.srs \
abcd1.srs \
abcdef.srs \
abcd.srs \
adaptlag.srs \
addm2.srs \
ahzhye.srs \
arconf.srs \
barions.srs \
barpf.srs \
bartdf.srs \
bfinpl.srs \
bfotpl.srs \
bindh.srs \
boostr.srs \
btmuhat.srs \
cheos.srs \
ckizun.srs \
coeff.srs \
cof.srs \
cohscat.srs \
colapse.srs \
cold.srs \
compres.srs \
cores.srs \
coscat2.srs \
coscat3.srs \
ddnu0.srs \
ddnu2.srs \
ddnu3.srs \
ddnu4.srs \
ddnu5.srs \
ddnu.srs \
difq3.srs \
difq.srs \
div4.srs \
divine.srs \
div.srs \
dorelag.srs \
dump.srs \
ecaptp.srs \
ecapt.srs \
ecapts.srs \
ecar.srs \
elecap.srs \
electra.srs \
emisabs.srs \
enrbal.srs \
eos141.srs \
eos14.srs \
eosfail.srs \
eosnuet.srs \
eosnu.srs \
eostab.srs \
eostry.srs \
eoswesty.srs \
etanu.srs \
fabc01.srs \
ffah.srs \
ffna.srs \
ffnp.srs \
ffx.srs \
fgam.srs \
fgs.srs \
fillyc.srs \
filly.srs \
findfk1.srs \
findfk.srs \
findnu.srs \
findroe.srs \
findtl.srs \
finish.srs \
frmi23.srs \
grstep.srs \
her3.srs \
highro.srs \
inconf.srs \
input.srs \
inter2.srs \
inter.srs \
invers2.srs \
joether.srs \
kesher.srs \
kramer.srs \
krina.srs \
ktiva.srs \
kvuim.srs \
locendb.srs \
locend.srs \
loceof.srs \
lochelm.srs \
makeenu.srs \
maketl.srs \
movlev.srs \
multm2.srs \
multv2.srs \
nesan.srs \
newtn1.srs \
newtn2.srs \
newton.srs \
newtye.srs \
nmconf.srs \
normy.srs \
nuabs.srs \
nuescat.srs \
nueta.srs \
nunup0.srs \
nurate.srs \
nuscat.srs \
pairate.srs \
peruk.srs \
pfname.srs \
plotdiv.srs \
poly.srs \
powers.srs \
prenu.srs \
printbal.srs \
printh.srs \
printn1.srs \
printn.srs \
printoc.srs \
prodrat.srs \
rashi.srs \
ratehp2.srs \
ratehp3.srs \
ratehp.srs \
rateh.srs \
ratemt.srs \
ratenub.srs \
ratenu.srs \
ratep.srs \
ratesp.srs \
rates.srs \
rddim.srs \
rdpar.srs \
rdveci.srs \
rdvec.srs \
readin.srs \
refilly.srs \
relager.srs \
relagn.srs \
relag.srs \
remark.srs \
restrt.srs \
rosp.srs \
rotepsb.srs \
rotepsc.srs \
roteps.srs \
rotepss.srs \
rotov.srs \
second.f \
selftest.srs \
setnup.srs \
state7.srs \
stateb.srs \
statec.srs \
statel.srs \
state.srs \
states.srs \
statez.srs \
subdd3.srs \
subdd.srs \
timstp.srs \
transfr.srs \
tridig1.srs \
tridig.srs \
trimat.srs \
troe.srs \
trop.srs \
tros.srs \
tubspf.srs \
viscosity.srs \
wrtalex.srs \
wrtconv.srs \
wrthead.srs \
wrtflux.srs \
wrtprof.srs \
wrtro.srs \
wrtshock.srs \
wtdim.srs \
wtpar.srs \
wtveci.srs \
wtvec.srs \
wwconf.srs \
wzconf.srs \
wznconf.srs \
zanav.srs \
zoning1.srs \
zoning2.srs \
zoning4.srs \
zoning5.srs \
zoning6.srs

objs =  abcd0.o \
abcd1.o \
abcdef.o \
abcd.o \
adaptlag.o \
addm2.o \
ahzhye.o \
arconf.o \
barions.o \
barpf.o \
bartdf.o \
bfinpl.o \
bfotpl.o \
bindh.o \
boostr.o \
btmuhat.o \
cheos.o \
ckizun.o \
coeff.o \
cof.o \
cohscat.o \
colapse.o \
cold.o \
compres.o \
cores.o \
coscat2.o \
coscat3.o \
ddnu0.o \
ddnu2.o \
ddnu3.o \
ddnu4.o \
ddnu5.o \
ddnu.o \
difq3.o \
difq.o \
div4.o \
divine.o \
div.o \
dorelag.o \
dump.o \
ecaptp.o \
ecapt.o \
ecapts.o \
ecar.o \
elecap.o \
electra.o \
emisabs.o \
enrbal.o \
eos141.o \
eos14.o \
eosfail.o \
eosnuet.o \
eosnu.o \
eostab.o \
eostry.o \
eoswesty.o \
etanu.o \
fabc01.o \
ffah.o \
ffna.o \
ffnp.o \
ffx.o \
fgam.o \
fgs.o \
fillyc.o \
filly.o \
findfk1.o \
findfk.o \
findnu.o \
findroe.o \
findtl.o \
finish.o \
frmi23.o \
grstep.o \
her3.o \
highro.o \
inconf.o \
input.o \
inter2.o \
inter.o \
invers2.o \
joether.o \
kesher.o \
kramer.o \
krina.o \
ktiva.o \
kvuim.o \
locendb.o \
locend.o \
loceof.o \
lochelm.o \
makeenu.o \
maketl.o \
movlev.o \
multm2.o \
multv2.o \
nesan.o \
newtn1.o \
newtn2.o \
newton.o \
newtye.o \
nmconf.o \
normy.o \
nuabs.o \
nuescat.o \
nueta.o \
nunup0.o \
nurate.o \
nuscat.o \
pairate.o \
peruk.o \
pfname.o \
plotdiv.o \
poly.o \
powers.o \
prenu.o \
printbal.o \
printh.o \
printn1.o \
printn.o \
printoc.o \
prodrat.o \
rashi.o \
ratehp2.o \
ratehp3.o \
ratehp.o \
rateh.o \
ratemt.o \
ratenub.o \
ratenu.o \
ratep.o \
ratesp.o \
rates.o \
rddim.o \
rdpar.o \
rdveci.o \
rdvec.o \
readin.o \
refilly.o \
relager.o \
relagn.o \
relag.o \
remark.o \
restrt.o \
rosp.o \
rotepsb.o \
rotepsc.o \
roteps.o \
rotepss.o \
rotov.o \
second.o \
selftest.o \
setnup.o \
state7.o \
stateb.o \
statec.o \
statel.o \
state.o \
states.o \
statez.o \
subdd3.o \
subdd.o \
timstp.o \
transfr.o \
tridig1.o \
tridig.o \
trimat.o \
troe.o \
trop.o \
tros.o \
tubspf.o \
viscosity.o \
wrtalex.o \
wrtconv.o \
wrthead.o \
wrtflux.o \
wrtprof.o \
wrtro.o \
wrtshock.o \
wtdim.o \
wtpar.o \
wtveci.o \
wtvec.o \
wwconf.o \
wzconf.o \
wznconf.o \
zanav.o \
zoning1.o \
zoning2.o \
zoning4.o \
zoning5.o \
zoning6.o \
ratebrem.o

bin = ../bin

include ../Makefile.opts

LIBS=-L../lib -lboom


boom: libboom.a  colapse.o
	$(FC) colapse.o  $(LIBS) $(SYSLIBS) -o boom

libboom.a: $(objs)
	ar crv libboom.a $(objs)
	install libboom.a ../lib
	rm -f libboom.a

install: boom
	install boom $(bin)

clean:
	rm -f $(objs) rashi.o rashi.F boom *.a *~ *.il ifc*

# .srs.o:
# 	$(bin)/prefort n comdecks $*.srs
# 	mv $*.f $*.F
# 	echo FFLAGS $(FFLAGS)
# 	$(FC) -c $(FFLAGS) $*.F -o $*.o
#	rm $*.F  ## SB commented out for debug
# 	echo *.F must be removed here

.IGNORE:

%.o : %.srs
	$(bin)/prefort n comdecks $*.srs
	mv $*.f $*.F
	echo FFLAGS $(FFLAGS)
	$(FC) -c $(FFLAGS) $*.F -o $*.o
##	rm $*.F  ## SB commented out for debug
	echo *.F must be removed here in standard setup
	
%.o: %.f
	$(FC) -c $(FFLAGS) $<

%.o: %.F
	$(FC) -c $(FFLAGS) $<


#Necessary because of a compiler bug on Intel 8.0
#Seems to be fixed as of 8,1,024
#rashi.o: rashi.F
#	$(bin)/prefort n comdecks $*.srs
#	mv $*.f $*.F
#	$(FC) -c $(FFLAGSBUG) rashi.F -o rashi.o

$(objs): comdecks Makefile
